name: Deployment to Heroku

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Replace ENV variables
        env:
            DB_ENDPOINT: ${{ secrets.DB_ENDPOINT }}
            DB_USERNAME: ${{ secrets.DB_USERNAME }}
            DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
            DB_NAME: ${{ secrets.DB_NAME }}
            API_PORT: ${{ secrets.API_PORT }}
            EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
            EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        run: perl -pi -e 's/__DB_ENDPOINT__/$ENV{DB_ENDPOINT}/' Dockerfile && perl -pi -e 's/__DB_USERNAME__/$ENV{DB_USERNAME}/' Dockerfile && perl -pi -e 's/__DB_PASSWORD__/$ENV{DB_PASSWORD}/' Dockerfile && perl -pi -e 's/__DB_NAME__/$ENV{DB_NAME}/' Dockerfile && perl -pi -e 's/__API_PORT__/$ENV{API_PORT}/' Dockerfile && perl -pi -e 's/__EMAIL_ADDRESS__/$ENV{EMAIL_ADDRESS}/' Dockerfile && perl -pi -e 's/__EMAIL_PASSWORD__/$ENV{EMAIL_PASSWORD}/' Dockerfile 
      - name: Compile Angular App
        run: cd frontend && npm install && npm install @angular/cli && npm run build-prod
      - name: Copy angular folder to backend public
        run: mv frontend/dist/frontend backend/public
      - name: Login to Heroku Container registry
        env: 
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:login 
      - name: Build and push
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:push -a ${{ secrets.HEROKU_APP_NAME }} web 
      - name: Release
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:release -a ${{ secrets.HEROKU_APP_NAME }} web 
